### ISSUE TITLE
阿里云盘规则

### ISSUE THREAD

**Issue by HahahaIoi** [RikkaApps/websites#49]
{
  "label": "阿里云盘",
  "package": "com.alicloud.databox",
  "authors": [
    ""
  ],
  "last_update": {
    "timestamp": 1639701068,
    "version_name": "2.3.0",
    "version_code": 76
  },
  "recommendation": "@recommended",
  "behaviors": [
    "@abuse"
  ],
  "export_folders": {
    "data": {
      "0": {
        "summary": "@saved_files",
        "source": "AliYunPan",
        "target": "Download/ALiYunPan",
        "call_media_scan": false,
        "add_to_downloads": true,
        "allow_child": false
      }
    }
  }
}

**Comment by LittleChest** [comment]
这里是网站仓库 不是存储空间隔离仓库
你应该在[这里]提交(https://github.com/RikkaApps/StorageRedirect-assets/issues/new/choose)
