### ISSUE TITLE
Link to name inspiration is not what is in the code

### ISSUE THREAD

**Issue by Tosoju** [RikkaApps/websites#89]
In https://github.com/RikkaApps/websites/edit/master/shizuku/introduction.md, the link goes to https://danbooru.donmai.us/posts/3553474

However, on the website it leads to https://www.pixiv.net/artworks/75508584, a dead link.

Just a small detail :)

**Comment by haruue** [comment]
[Amashiro Natsuki](https://www.pixiv.net/users/3036679), the artist of the character Shizuku, has deleted all her artwork on Pixiv, including this one.

We have no idea why this happened, but we want to leave this citation anyway.
